# coding: utf-8

"""
mmopdca API

Command-DSL-driven forecasting micro-service API only

The version of the OpenAPI document: 0.4.0
Contact: gtocue510@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.act_action import ActAction


class TestActAction(unittest.TestCase):
    """ActAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActAction(self):
        """Test ActAction"""
        # inst = ActAction()


if __name__ == "__main__":
    unittest.main()
