# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.check_report import CheckReport

class TestCheckReport(unittest.TestCase):
    """CheckReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckReport:
        """Test CheckReport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckReport`
        """
        model = CheckReport()
        if include_optional:
            return CheckReport(
                r2 = -1.0,
                threshold = -1.0,
                passed = True
            )
        else:
            return CheckReport(
                r2 = -1.0,
                threshold = -1.0,
                passed = True,
        )
        """

    def testCheckReport(self):
        """Test CheckReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
