# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.plan_response import PlanResponse

class TestPlanResponse(unittest.TestCase):
    """PlanResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanResponse:
        """Test PlanResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanResponse`
        """
        model = PlanResponse()
        if include_optional:
            return PlanResponse(
                id = '',
                symbol = '',
                start = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                created_at = ''
            )
        else:
            return PlanResponse(
                id = '',
                symbol = '',
                created_at = '',
        )
        """

    def testPlanResponse(self):
        """Test PlanResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
