# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.api.metrics_api import MetricsApi


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsApi()

    def tearDown(self) -> None:
        pass

    def test_get_metric_value_metrics_name_get(self) -> None:
        """Test case for get_metric_value_metrics_name_get

        Get instant metric value
        """
        pass

    def test_list_metrics_metrics_get(self) -> None:
        """Test case for list_metrics_metrics_get

        List metric catalog
        """
        pass


if __name__ == '__main__':
    unittest.main()
