# coding: utf-8

"""
mmopdca API

Command-DSL-driven forecasting micro-service API only

The version of the OpenAPI document: 0.4.0
Contact: gtocue510@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.api.check_api import CheckApi


class TestCheckApi(unittest.TestCase):
    """CheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckApi()

    def tearDown(self) -> None:
        pass

    def test_enqueue_check_check_do_id_post(self) -> None:
        """Test case for enqueue_check_check_do_id_post

        Enqueue Check job (Celery)
        """
        pass

    def test_get_check_check_check_id_get(self) -> None:
        """Test case for get_check_check_check_id_get

        Get Check record
        """
        pass

    def test_get_check_status_check_status_task_id_get(self) -> None:
        """Test case for get_check_status_check_status_task_id_get

        Raw Celery task state
        """
        pass

    def test_list_check_check_get(self) -> None:
        """Test case for list_check_check_get

        List Check records
        """
        pass


if __name__ == "__main__":
    unittest.main()
