# coding: utf-8

"""
mmopdca API

Command-DSL-driven forecasting micro-service API only

The version of the OpenAPI document: 0.4.0
Contact: gtocue510@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.api.plan_api import PlanApi


class TestPlanApi(unittest.TestCase):
    """PlanApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlanApi()

    def tearDown(self) -> None:
        pass

    def test_create_plan_plan_post(self) -> None:
        """Test case for create_plan_plan_post

        Create Plan
        """
        pass

    def test_delete_plan_plan_plan_id_delete(self) -> None:
        """Test case for delete_plan_plan_plan_id_delete

        Delete Plan
        """
        pass

    def test_get_plan_plan_plan_id_get(self) -> None:
        """Test case for get_plan_plan_plan_id_get

        Get Plan by ID
        """
        pass

    def test_list_plans_plan_get(self) -> None:
        """Test case for list_plans_plan_get

        List Plans
        """
        pass


if __name__ == "__main__":
    unittest.main()
