# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.do_response import DoResponse

class TestDoResponse(unittest.TestCase):
    """DoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DoResponse:
        """Test DoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DoResponse`
        """
        model = DoResponse()
        if include_optional:
            return DoResponse(
                do_id = '',
                plan_id = '',
                seq = 1.0,
                run_tag = '',
                status = 'PENDING',
                result = None,
                artifact_uri = '',
                dashboard_url = '0'
            )
        else:
            return DoResponse(
                do_id = '',
                plan_id = '',
                seq = 1.0,
                status = 'PENDING',
        )
        """

    def testDoResponse(self):
        """Test DoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
