# coding: utf-8

"""
mmopdca API

Command-DSL-driven forecasting micro-service API only

The version of the OpenAPI document: 0.4.0
Contact: gtocue510@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.api.plan_dsl_api import PlanDslApi


class TestPlanDslApi(unittest.TestCase):
    """PlanDslApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlanDslApi()

    def tearDown(self) -> None:
        pass

    def test_create_plan_dsl_plan_dsl_post(self) -> None:
        """Test case for create_plan_dsl_plan_dsl_post

        Create Plan from DSL (YAML / JSON)
        """
        pass

    def test_get_plan_dsl_plan_dsl_plan_id_get(self) -> None:
        """Test case for get_plan_dsl_plan_dsl_plan_id_get

        Get DSL Plan
        """
        pass

    def test_list_plans_dsl_plan_dsl_get(self) -> None:
        """Test case for list_plans_dsl_plan_dsl_get

        List DSL Plans
        """
        pass


if __name__ == "__main__":
    unittest.main()
