# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.do_status import DoStatus

class TestDoStatus(unittest.TestCase):
    """DoStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoStatus(self):
        """Test DoStatus"""
        # inst = DoStatus()

if __name__ == '__main__':
    unittest.main()
