# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.indicator_param import IndicatorParam

class TestIndicatorParam(unittest.TestCase):
    """IndicatorParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndicatorParam:
        """Test IndicatorParam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndicatorParam`
        """
        model = IndicatorParam()
        if include_optional:
            return IndicatorParam(
                name = 'SMA',
                window = 1.0
            )
        else:
            return IndicatorParam(
        )
        """

    def testIndicatorParam(self):
        """Test IndicatorParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
