# coding: utf-8

"""
    mmopdca API

    Command-DSL-driven forecasting micro-service API only

    The version of the OpenAPI document: 0.4.0
    Contact: gtocue510@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mmopdca_sdk.models.metric_value import MetricValue

class TestMetricValue(unittest.TestCase):
    """MetricValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricValue:
        """Test MetricValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricValue`
        """
        model = MetricValue()
        if include_optional:
            return MetricValue(
                name = '',
                unit = '',
                slo = 1.337,
                var_class = 'S',
                ts = 56,
                value = 1.337
            )
        else:
            return MetricValue(
                name = '',
                var_class = 'S',
                ts = 56,
                value = 1.337,
        )
        """

    def testMetricValue(self):
        """Test MetricValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
