# ======================================================================
# prom/prometheus.yml — mmopdca Prometheus 設定ファイル
# ======================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules_mmopdca.yml   # ← 下で書き換え

scrape_configs:
  - job_name: celery-exporter
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
