################################################################################
# compose.override.yml – 外へ晒さず / メモリ爆死させず / TLS 終端を付加
################################################################################
services:
  # ───────────────────── Redis (LAN 内専用 + 認証 + LRU 256 MB)
  redis:
    ports: [] # 6379 を閉じる
    secrets: [ redis_pwd ]
    command:
      - redis-server
      - "--requirepass"
      - "/run/secrets/redis_pwd" # ← ファイルパスを文字列で
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "allkeys-lru"

  # ───────────────────── Postgres も外ポート閉鎖
  db:
    ports: []

  # ───────────────────── Grafana も Reverse-Proxy 経由だけに
  grafana:
    ports: []

  # ───────────────────── 1 枚だけ外に出す HTTPS Nginx
  nginx:
    image: nginx:1.27-alpine
    container_name: mmopdca-nginx
    ports: [ "443:443" ] # HTTPS だけ公開
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ops/cert.pem:/etc/nginx/cert.pem:ro
      - ./ops/key.pem:/etc/nginx/key.pem:ro
    depends_on: [ api, grafana ]
    restart: unless-stopped
    networks: [ default ]

# ───────────────────── Docker Secret (先に作成しておく)
secrets:
  redis_pwd:
    external: true
