version: "3.9"

services:
  # ───────────────────────────── API
  api:
    build:
      context: .
      dockerfile: Dockerfile.main_api
    user: "0:0"
    volumes:
      - dsl_data:/mnt/data/dsl # ← bind-mount 削除

  # ───────────────────────────── Worker
  worker:
    user: "0:0"
    command: [ "celery", "-A", "core.celery_app:celery_app", "worker", "--loglevel=info" ]
    volumes:
      - dsl_data:/mnt/data/dsl
      - checkpoints_data:/mnt/checkpoints # ← bind-mount 削除

  # ───────────────────────────── Beat
  beat:
    user: "0:0"
    command:
      - celery
      - -A
      - core.celery_app:celery_app
      - beat
      - --loglevel=info
      - --schedule=/mnt/checkpoints/celerybeat-schedule
    volumes:
      - dsl_data:/mnt/data/dsl
      - checkpoints_data:/mnt/checkpoints # ← bind-mount 削除

  # ───────────────────────────── Flower / Prom / Grafana
  flower:
    image: mher/flower:1.2
    ports: [ "5555:5555" ]

  prom:
    image: prom/prometheus:v2.52.0
    ports: [ "9090:9090" ]

  grafana:
    image: grafana/grafana-oss:10.4.2
    ports: [ "3000:3000" ]

  # ───────────────────────────── Exporters
  celery-exporter:
    image: danihodovic/celery-exporter:0.9.1
    environment:
      - CELERY_BROKER_URL=redis://default:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      redis: { condition: service_started }
    ports: [ "9808:9808" ]
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:v1.60.0
    command: [ "--redis.addr=redis://default:${REDIS_PASSWORD}@redis:6379" ]
    depends_on:
      redis: { condition: service_started }
    ports: [ "9121:9121" ]
    restart: unless-stopped

volumes:
  dsl_data:
  checkpoints_data:
