# ──────────────────────────────────────────────────────────────
# pyproject.toml  ―  “アプリ本体” を Poetry でビルドする完全版
#   * ルートを 1 つの **Python パッケージ** として扱うため
#     package-mode = true へ変更
#   * tests／SDK は除外（SDK は sdk-py/ 側で独立管理）
# ──────────────────────────────────────────────────────────────
[tool.poetry]
name         = "mmopdca"
version      = "0.1.0"
description  = "Command-DSL-driven forecasting SaaS (MVP)"
authors      = ["gtocue <gtocue510@gmail.com>"]
license      = "MIT"
readme       = "README.md"
package-mode = true            # ← Poetry に「パッケージ扱い」と宣言

packages = [
  { include = "api"         },
  { include = "core"        },
  { include = "plugins"     },
  { include = "common_core" }
]

[tool.poetry.dependencies]
python            = ">=3.11,<3.13"
fastapi           = ">=0.111,<0.117"
uvicorn           = { version = ">=0.29,<0.32", extras = ["standard"] }
python-multipart  = "^0.0.8"
pydantic          = "^2.7.2"
python-dotenv     = "^1.0"
fastjsonschema    = "^2.21.0"
cachetools        = "^5.3"
requests          = "^2.32"
prometheus-client = "^0.20"
pandas            = "^2.2"
numpy             = "^2.2"
scikit-learn      = "^1.6"
yfinance          = ">=0.2,<0.3"
plotly            = "^6.0"
celery            = { version = "^5.3", extras = ["redis"] }
redis             = "^5.0"
psycopg           = { version = ">=3.1,<4.0", extras = ["binary"] }
alembic           = "^1.15"

[tool.poetry.group.dev.dependencies]
pytest    = "^8.3"
black     = "^25"
isort     = "^6"
ruff      = "^0.4"
mypy      = "^1.10"
httpx     = "^0.27"
pyarrow   = "^12.0"

[tool.poetry.plugins."mmopdca_adapters"]
stock_us = "plugins.stock_us.adapter:StockUSAdapter"

[tool.poe.tasks]
test      = "pytest -q"
lint      = "ruff ."
format    = "ruff format . && isort . && black ."
typecheck = "mypy ."
migrate   = "alembic upgrade head"

[build-system]
requires      = ["poetry-core>=2.0,<3.0"]
build-backend = "poetry.core.masonry.api"