# ----------------------------------------------------------
# pyproject.toml — mmopdca root
#   * PEP 621 metadata          : [project] section
#   * Runtime dependencies      : project.dependencies
#   * Dev / CI dependencies     : [tool.poetry.group.dev.dependencies]
#   * Optional DB dependencies  : [tool.poetry.group.db.dependencies]
#   * Adapter entry-points      : [project.entry-points."mmopdca_adapters"]
#   * Build backend             : poetry-core
# ----------------------------------------------------------

[project]
name            = "mmopdca"
version         = "0.1.0"
description     = "command-DSL-driven forecasting app (pivot-ready)"
authors         = [{ name = "gtocue", email = "gtocue510@gmail.com" }]
license         = { text = "MIT" }
readme          = "README.md"
requires-python = ">=3.11,<3.13"

# ---------- Runtime dependencies ----------
dependencies = [
  "fastapi>=0.115.12,<0.116.0",
  "pydantic>=2.7.2,<3.0.0",
  "uvicorn[standard]>=0.34.2,<0.35.0",
  "python-dotenv>=1.1.0,<2.0.0",
  "pytz>=2025.2,<2026.0",
  "pandas>=2.2.3,<3.0.0",
  "numpy>=2.2.5,<3.0.0",
  "scikit-learn>=1.6.1,<2.0.0",
  "yfinance>=0.2.56,<0.3.0",
  "plotly>=6.0.1,<7.0.0"
]

# ---------- Adapter entry-points ----------
[project.entry-points."mmopdca_adapters"]
stock_us = "plugins.stock_us.adapter:StockUSAdapter"

# ---------- Poetry settings ----------
[tool.poetry]
package-mode = true   # needed for entry-points

[[tool.poetry.packages]]
include = "common_core"

[[tool.poetry.packages]]
include = "plugins"

# ---------- Dev / CI dependencies ----------
[tool.poetry.group.dev.dependencies]
pytest  = "^8.3.5"
black   = "^25.1.0"
isort   = "^6.0.1"
mypy    = "^1.15.0"
alembic = "^1.15.2"

# ---------- Optional DB dependencies ----------
[tool.poetry.group.db.dependencies]
psycopg = { version = ">=3.1,<4.0.0", extras = ["binary"] }

# ---------- Build backend ----------
[build-system]
requires      = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
