[project]
name = "mmopdca"
version = "0.1.0"
description = "命令書型予測アプリ (pivot-ready)"
authors = [
    {name = "gtocue",email = "gtocue510@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "pydantic-core (>=2.34.1,<3.0.0)",
    "uvicorn[standard] (>=0.34.2,<0.35.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "pytz (>=2025.2,<2026.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "numpy (>=2.2.5,<3.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "yfinance (>=0.2.56,<0.3.0)",
    "plotly (>=6.0.1,<7.0.0)"
]

[tool.poetry]
package-mode = false   # ← ★ ここに移す

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
