/* tslint:disable */
/* eslint-disable */
/**
 * mmopdca API
 * Command-DSL-driven forecasting micro-service API only
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: gtocue510@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 可変キーを許容する緩いメトリクスモデル。
 * デフォルト項目として r2 / threshold / passed を持ち、
 * 追加指標 (rmse, mape など) は extra="allow" で拡張可能。
 * @export
 * @interface CheckReport
 */
export interface CheckReport {
    [key: string]: any | any;
    /**
     * 決定係数
     * @type {number}
     * @memberof CheckReport
     */
    r2: number;
    /**
     * 合格ライン
     * @type {number}
     * @memberof CheckReport
     */
    threshold: number;
    /**
     * 閾値をクリアしたら True
     * @type {boolean}
     * @memberof CheckReport
     */
    passed: boolean;
}

/**
 * Check if a given object implements the CheckReport interface.
 */
export function instanceOfCheckReport(value: object): value is CheckReport {
    if (!('r2' in value) || value['r2'] === undefined) return false;
    if (!('threshold' in value) || value['threshold'] === undefined) return false;
    if (!('passed' in value) || value['passed'] === undefined) return false;
    return true;
}

export function CheckReportFromJSON(json: any): CheckReport {
    return CheckReportFromJSONTyped(json, false);
}

export function CheckReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckReport {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'r2': json['r2'],
        'threshold': json['threshold'],
        'passed': json['passed'],
    };
}

export function CheckReportToJSON(json: any): CheckReport {
    return CheckReportToJSONTyped(json, false);
}

export function CheckReportToJSONTyped(value?: CheckReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'r2': value['r2'],
        'threshold': value['threshold'],
        'passed': value['passed'],
    };
}

