/* tslint:disable */
/* eslint-disable */
/**
 * mmopdca API
 * Command-DSL-driven forecasting micro-service API only
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: gtocue510@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IndicatorParam } from './IndicatorParam';
import {
    IndicatorParamFromJSON,
    IndicatorParamFromJSONTyped,
    IndicatorParamToJSON,
    IndicatorParamToJSONTyped,
} from './IndicatorParam';

/**
 * Do フェーズ実行リクエスト。
 * 
 * すべて **任意**。未指定項目は対応する Plan の値を継承する。
 * @export
 * @interface DoCreateRequest
 */
export interface DoCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof DoCreateRequest
     */
    symbol?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DoCreateRequest
     */
    start?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DoCreateRequest
     */
    end?: Date | null;
    /**
     * 
     * @type {Array<IndicatorParam>}
     * @memberof DoCreateRequest
     */
    indicators?: Array<IndicatorParam> | null;
    /**
     * 
     * @type {number}
     * @memberof DoCreateRequest
     */
    runNo?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DoCreateRequest
     */
    seq?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DoCreateRequest
     */
    runTag?: string | null;
}

/**
 * Check if a given object implements the DoCreateRequest interface.
 */
export function instanceOfDoCreateRequest(value: object): value is DoCreateRequest {
    return true;
}

export function DoCreateRequestFromJSON(json: any): DoCreateRequest {
    return DoCreateRequestFromJSONTyped(json, false);
}

export function DoCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'indicators': json['indicators'] == null ? undefined : ((json['indicators'] as Array<any>).map(IndicatorParamFromJSON)),
        'runNo': json['run_no'] == null ? undefined : json['run_no'],
        'seq': json['seq'] == null ? undefined : json['seq'],
        'runTag': json['run_tag'] == null ? undefined : json['run_tag'],
    };
}

export function DoCreateRequestToJSON(json: any): DoCreateRequest {
    return DoCreateRequestToJSONTyped(json, false);
}

export function DoCreateRequestToJSONTyped(value?: DoCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'start': value['start'] == null ? undefined : ((value['start'] as any).toISOString().substring(0,10)),
        'end': value['end'] == null ? undefined : ((value['end'] as any).toISOString().substring(0,10)),
        'indicators': value['indicators'] == null ? undefined : ((value['indicators'] as Array<any>).map(IndicatorParamToJSON)),
        'run_no': value['runNo'],
        'seq': value['seq'],
        'run_tag': value['runTag'],
    };
}

