/* tslint:disable */
/* eslint-disable */
/**
 * mmopdca API
 * Command-DSL-driven forecasting micro-service API only
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: gtocue510@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DoStatus = {
    Pending: 'PENDING',
    Running: 'RUNNING',
    Done: 'DONE',
    Failed: 'FAILED'
} as const;
export type DoStatus = typeof DoStatus[keyof typeof DoStatus];


export function instanceOfDoStatus(value: any): boolean {
    for (const key in DoStatus) {
        if (Object.prototype.hasOwnProperty.call(DoStatus, key)) {
            if (DoStatus[key as keyof typeof DoStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DoStatusFromJSON(json: any): DoStatus {
    return DoStatusFromJSONTyped(json, false);
}

export function DoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoStatus {
    return json as DoStatus;
}

export function DoStatusToJSON(value?: DoStatus | null): any {
    return value as any;
}

export function DoStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DoStatus {
    return value as DoStatus;
}

