/* tslint:disable */
/* eslint-disable */
/**
 * mmopdca API
 * Command-DSL-driven forecasting micro-service API only
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: gtocue510@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 追加計算したいテクニカル指標パラメータ。
 * 
 * *MVP* では `name="SMA"` だけを想定するが、後方互換を考慮して
 * 任意文字列を許容している。
 * @export
 * @interface IndicatorParam
 */
export interface IndicatorParam {
    /**
     * 指標名
     * @type {string}
     * @memberof IndicatorParam
     */
    name?: string;
    /**
     * 計算ウィンドウ（日／バー数）
     * @type {number}
     * @memberof IndicatorParam
     */
    window?: number;
}

/**
 * Check if a given object implements the IndicatorParam interface.
 */
export function instanceOfIndicatorParam(value: object): value is IndicatorParam {
    return true;
}

export function IndicatorParamFromJSON(json: any): IndicatorParam {
    return IndicatorParamFromJSONTyped(json, false);
}

export function IndicatorParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndicatorParam {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'window': json['window'] == null ? undefined : json['window'],
    };
}

export function IndicatorParamToJSON(json: any): IndicatorParam {
    return IndicatorParamToJSONTyped(json, false);
}

export function IndicatorParamToJSONTyped(value?: IndicatorParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'window': value['window'],
    };
}

