/* tslint:disable */
/* eslint-disable */
/**
 * mmopdca API
 * Command-DSL-driven forecasting micro-service API only
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: gtocue510@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportAnyOfValue
 */
export interface ReportAnyOfValue {
}

/**
 * Check if a given object implements the ReportAnyOfValue interface.
 */
export function instanceOfReportAnyOfValue(value: object): value is ReportAnyOfValue {
    return true;
}

export function ReportAnyOfValueFromJSON(json: any): ReportAnyOfValue {
    return ReportAnyOfValueFromJSONTyped(json, false);
}

export function ReportAnyOfValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportAnyOfValue {
    return json;
}

export function ReportAnyOfValueToJSON(json: any): ReportAnyOfValue {
    return ReportAnyOfValueToJSONTyped(json, false);
}

export function ReportAnyOfValueToJSONTyped(value?: ReportAnyOfValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

