# docker/compose.ports.yml
version: "3.9"

services:
  api:
    ports:
      - "8001:8001"

  redis:
    ports:
      - "6379:6379"

  db:
    ports:
      - "5432:5432"

  prom:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  redis-exporter:
    ports:
      - "9121:9121"

  celery-exporter:
    ports:
      - "9808:9808"

networks:
  mmopdca_default:
    external: true
