# docker/compose.dash.plan.yml  笏笏 Dash 窶徘lan窶・繧ｵ繝ｼ繝薙せ髮帛ｽ｢
x-default_env: &default_env
  DSL_ROOT: ${DSL_ROOT}

x-dash_template: &dash_template
  image: dash-base:latest
  restart: unless-stopped

services:
  plan:
    <<: *dash_template
    environment:
      <<: *default_env
      SERVICE_NAME: plan

