# docker/compose.db.yml
version: "3.9"

services:
  # ─────────────────────────── Redis
  redis:
    image: redis:7-alpine
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
                   --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes: [ redis_data:/data ]
    restart: unless-stopped

  # ─────────────────────────── PostgreSQL
  db:
    image: postgres:16-alpine
    env_file: [ ../.env ]
    volumes: [ pg_data:/var/lib/postgresql/data ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
