version: "3.9" # v3.9 警告は無害

services:
  db:
    image: postgres:15-alpine
    env_file: [ ../.env ]

    volumes:
      - pg_data:/var/lib/postgresql/data

    # $${VAR} でホスト展開を止め、コンテナ内で評価
    healthcheck:
      test:
        - CMD-SHELL
        - >
          PGPASSWORD=$${POSTGRES_PASSWORD} pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -q
      interval: 10s
      timeout: 5s
      retries: 5

    networks: [ mmopdca_default ]
    restart: unless-stopped

volumes:
  pg_data:


networks:
  mmopdca_default:
    external: true
