# docker/compose.exporter.redis.yml  ★修正版
services:
  redis-exporter:
    image: oliver006/redis_exporter:v1.60.0
    env_file:
      - ../.env

    # --- ここも同じ考え方 ---------------------------------
    command:
      - '--redis.addr=redis://:${REDIS_PASSWORD}@redis:6379/0'
    # ------------------------------------------------------

    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:9121/metrics || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis: { condition: service_healthy }
