version: "3.9"

services:
  redis:
    image: redis:7-alpine

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  api:
    build:
      context: ..
      dockerfile: Dockerfile.main_api
    environment:
      DATABASE_URL: postgresql://test:test@db:5432/test
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - db
