version: "3.9"

services:
  # ── Core ───────────────────────────────────────────────────────
  api: { ports: [ "8001:8001" ] }
  grafana: { ports: [ "3000:3000" ] }
  prom: { ports: [ "9090:9090" ] }
  flower: { ports: [ "5555:5555" ] }
  celery-exporter: { ports: [ "9808:9808" ] }
  redis-exporter: { ports: [ "9121:9121" ] }
  # Dash 系 (mother / master / orch / ops / plan / do / check / act)
  # ⇒ すべて **不要** のためエントリを削除
