version: "3.9"

services:
  beat:
    build:
      context: ..
      dockerfile: Dockerfile
      target: runtime
    user: root
    env_file: [ ../.env ]
    environment:
      - DSL_ROOT
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - DO_TOTAL_SHARDS
    working_dir: /mnt/checkpoints
    entrypoint: [ /usr/local/bin/docker-entrypoint-init-dsl.sh ]
    command: [ celery, -A, core.celery_app:celery_app, beat, --loglevel=info, --schedule=/mnt/checkpoints/celerybeat-schedule ]
    volumes:
      - checkpoints_data:/mnt/checkpoints
      - dsl_data:/mnt/data/dsl
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    networks: [ mmopdca_default ]
    restart: on-failure
