services:
  redis-exporter:
    build:
      context: ./redis-exporter       # ← フォルダをビルドコンテキストに
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command:
      - "--redis.addr=redis://default:${REDIS_PASSWORD_ENC}@redis:6379"
    ports:
      - "9121:9121"
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - mmopdca_default

networks:
  mmopdca_default:
    name: mmopdca_default
