services:
  celery-exporter:
    image: danihodovic/celery-exporter:0.9.1
    env_file: [ ../.env ]
    environment:
      CE_BROKER_URL: "redis://default:${REDIS_PASSWORD_ENC}@redis:6379/0"
      CE_PORT: "9808"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9808/metrics" ]
      interval: 5s
      timeout: 3s
      retries: 12
