services:
  beat:
    # Celery Beat を直接起動するコマンドに変更
    command:
      - celery
      - -A
      - core.celery_app:celery_app
      - beat
      - --loglevel=info
    # …（以下は既存の entrypoint, environment, volumes 等そのまま）


