# ファイル: docker/compose.exporter.redis.yml
# 目的: Redis-Exporter を単独サービスとして起動し、ポート9121でメトリクスを公開（ヘルスチェック無効化）

services:
  redis-exporter:
    image: oliver006/redis_exporter:v1.60.0
    command:
      - "--redis.addr=redis://default:${REDIS_PASSWORD_ENC}@redis:6379"
    restart: unless-stopped
    healthcheck:
      disable: true
    ports:
      - "9121:9121"
