services:
  api:
    ports:
      - "8001:8001"

  redis:
    ports:
      - "${HOST_REDIS_PORT:-6379}:6379"

  db:
    ports:
      - "${HOST_POSTGRES_PORT:-5432}:5432"

  prom:
    ports:
      - "${HOST_PROM_PORT:-19090}:9090"

  grafana:
    ports:
      - "3000:3000"

  redis-exporter:
    ports:
      - "9121:9121"

  celery-exporter:
    ports:
      - "9808:9808"

networks:
  mmopdca_default:
    name: mmopdca_default
