version: "3.9"

services:
  redis-exporter:
    build:
      context: .
      dockerfile: Dockerfile.redis-exporter
    env_file:
      - ../.env
    command:
      - "--redis.addr=redis://default:${REDIS_PASSWORD_ENC}@redis:6379"
    ports:
      - "9121:9121"
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - mmopdca_default

networks:
  mmopdca_default:
    external: true
