# docker/compose.db.yml
version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -q" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mmopdca_default
    restart: unless-stopped

volumes:
  pg_data:


networks:
  mmopdca_default:
    external: true
