# docker/compose.beat.yml
services:
  beat:
    command:
      - celery
      - -A
      - core.celery_app:celery_app
      - beat
      - --loglevel=info
      - --schedule=/mnt/checkpoints/celerybeat-schedule
