# docker/compose.db.yml
services:
  db:
    image: postgres:16-alpine

    # ↓ ここで直接渡す
    environment:
      - POSTGRES_USER=mmop_user
      - POSTGRES_PASSWORD=SuperSafePgPassw0rd!
      - POSTGRES_DB=mmopdca

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -q"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - mmopdca_default

    restart: unless-stopped

volumes:
  pg_data:

networks:
  mmopdca_default:
    external: true
