# docker/compose.ci.yml
# ──────────────────────────────────────────────────────────────
# GitHub Actions “stack-health” ワークフロー専用
# ・redis / postgres / api（FastAPI）＋3 Exporters＋Prometheus
# ・`.env` は CI ステップでリポジトリ直下に動的生成されるため
#   `env_file: [ ../.env ]` とする
# ──────────────────────────────────────────────────────────────

##################### 共通オプション #####################
x-env: &default-env
  env_file: [ ../.env ] # ← リポジトリ直下の .env を参照

x-retry: &retry
  interval: 10s
  timeout: 3s
  retries: 3

######################## services ########################
services:
  # ---------- Core ----------
  redis:
    image: redis:7-alpine
    <<: *default-env
    command: [ "redis-server", "--requirepass=" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      <<: *retry
    ports: [ "6379:6379" ]

  db:
    image: postgres:16-alpine
    <<: *default-env
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      <<: *retry
    ports: [ "5432:5432" ]

  api:
    build:
      context: ..
      dockerfile: Dockerfile.main_api
    <<: *default-env
    environment:
      DSL_ROOT: /mnt/data/dsl
    depends_on: [ redis, db ]
    ports: [ "8001:8001" ]
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8001/docs" ]
      <<: *retry

  # ---------- Exporters ----------
  redis-exporter:
    image: oliver006/redis_exporter:v1.60.0
    command: [ "--redis.addr=redis://redis:6379/0" ]
    depends_on: [ redis ]
    ports: [ "9121:9121" ]

  celery-exporter:
    image: danihodovic/celery-exporter:0.9.1
    environment:
      CE_BROKER_URL: redis://redis:6379/0
      CE_BACKEND_URL: redis://redis:6379/0
      CE_PORT: 9808
    depends_on: [ redis ]
    ports: [ "9808:9808" ]

  # ---------- Prometheus ----------
  prom:
    image: prom/prometheus:v2.52.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=14d"
    volumes:
      - ../prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on: [ redis-exporter, celery-exporter ]
    ports: [ "9090:9090" ]

######################## volumes ########################
volumes: {}
