version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file: [ ../.env ] # ← すでに OK
    environment:
      # 変数が .env から展開される
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-UTC}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
    restart: unless-stopped

volumes:
  pg_data:
