services:
  # Redis 笏笏 繧ｭ繝｣繝・す繝･ / 繝悶Ο繝ｼ繧ｫ繝ｼ
  redis:
    image: redis:7-alpine
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
                   --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # PostgreSQL 笏笏 繧｢繝励Μ DB
  db:
    image: postgres:16-alpine
    env_file: [ ../.env ]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
