# docker/compose.exporter.celery.yml  ★修正版
services:
  celery-exporter:
    image: danihodovic/celery-exporter:0.9.1

    # ルート .env を読む
    env_file:
      - ../.env

    # ---- ここがポイント ------------------------------
    environment:
      # Compose の変数展開は ${VAR} を使う
      CE_BROKER_URL: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      CE_PORT: "9808"
    # --------------------------------------------------

    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:9808/metrics || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis: { condition: service_healthy }
