# docker/compose.db.yml
#
# ─────────────────────────────────────────────────────────────
# “動けばいい” ではなく、後々 17-alpine に上げても崩れない
# 最小構成で PostgreSQL 16 を起動します。
# ─────────────────────────────────────────────────────────────

services:
  db:
    image: postgres:16-alpine
    container_name: mmopdca-db

    # ────── 初期ユーザー / パスワード / DB ──────
    # env_file を使わず literals に固定
    environment:
      POSTGRES_USER:     mmop_user
      POSTGRES_PASSWORD: SuperSafePgPassw0rd!
      POSTGRES_DB:       mmopdca
      TZ:                UTC               # ログ時刻ずれ防止（任意）

    # ────── ポート公開 ──────
    ports:
      - "5432:5432"

    # ────── データ永続化 ──────
    volumes:
      - pg_data:/var/lib/postgresql/data

    # ────── コンテナ健全性チェック ──────
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mmop_user -d mmopdca -q"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    networks:
      - mmopdca_default

# ────────────── 追加定義 ──────────────
volumes:
  pg_data: {}

networks:
  mmopdca_default:
    driver: bridge
