# ファイル: docker/compose.alert.yml
# 目的: Alertmanager を SMTP 設定付きで起動し、ポート公開は ports.yml で一元管理

services:
  alertmanager:
    build:
      context: .
      dockerfile: Dockerfile.alertmanager
    image: mmopdca_alertmanager:latest
    env_file:
      - ../.env
    environment:
      - SMTP_SMARTHOST
      - SMTP_FROM
      - ALERTMAIL_TO
      - SG_USER
      - SG_PASS
    restart: unless-stopped
    healthcheck:
      disable: true
