services:
  celery-exporter:
    build:
      context: ./celery-exporter      # ← フォルダをビルドコンテキストに
      dockerfile: Dockerfile          # ← 中の Dockerfile 名
    env_file:
      - ../.env
    environment:
      # .env で REDIS_PASSWORD_ENC を定義しておく
      - CE_BROKER_URL=redis://default:${REDIS_PASSWORD_ENC}@redis:6379/0
      - CE_PORT=9808
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - mmopdca_default

networks:
  mmopdca_default:
    name: mmopdca_default
