/* tslint:disable */
/* eslint-disable */
/**
 * mmopdca API
 * Command-DSL-driven forecasting micro-service API only
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: gtocue510@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  PlanResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PlanResponseFromJSON,
    PlanResponseToJSON,
} from '../models/index';

export interface CreatePlanDslPlanDslPostRequest {
    file?: Blob | null;
}

export interface GetPlanDslPlanDslPlanIdGetRequest {
    planId: string;
}

/**
 * 
 */
export class PlanDslApi extends runtime.BaseAPI {

    /**
     * DSL ファイル *または* 生テキスト body を受け取り Plan を登録。  **PowerShell 例**  ```powershell $yaml = Get-Content .\\samples\\plan_mvp.yaml -Raw Invoke-RestMethod `   -Uri \'http://localhost:8001/plan-dsl/\' `   -Method Post `   -Body $yaml `   -ContentType \'application/x-yaml\' ```
     * Create Plan from DSL (YAML / JSON)
     */
    async createPlanDslPlanDslPostRaw(requestParameters: CreatePlanDslPlanDslPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlanResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/plan-dsl/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanResponseFromJSON(jsonValue));
    }

    /**
     * DSL ファイル *または* 生テキスト body を受け取り Plan を登録。  **PowerShell 例**  ```powershell $yaml = Get-Content .\\samples\\plan_mvp.yaml -Raw Invoke-RestMethod `   -Uri \'http://localhost:8001/plan-dsl/\' `   -Method Post `   -Body $yaml `   -ContentType \'application/x-yaml\' ```
     * Create Plan from DSL (YAML / JSON)
     */
    async createPlanDslPlanDslPost(requestParameters: CreatePlanDslPlanDslPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlanResponse> {
        const response = await this.createPlanDslPlanDslPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get DSL Plan
     */
    async getPlanDslPlanDslPlanIdGetRaw(requestParameters: GetPlanDslPlanDslPlanIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlanResponse>> {
        if (requestParameters['planId'] == null) {
            throw new runtime.RequiredError(
                'planId',
                'Required parameter "planId" was null or undefined when calling getPlanDslPlanDslPlanIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/plan-dsl/{plan_id}`.replace(`{${"plan_id"}}`, encodeURIComponent(String(requestParameters['planId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanResponseFromJSON(jsonValue));
    }

    /**
     * Get DSL Plan
     */
    async getPlanDslPlanDslPlanIdGet(requestParameters: GetPlanDslPlanDslPlanIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlanResponse> {
        const response = await this.getPlanDslPlanDslPlanIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List DSL Plans
     */
    async listPlansDslPlanDslGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlanResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/plan-dsl/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlanResponseFromJSON));
    }

    /**
     * List DSL Plans
     */
    async listPlansDslPlanDslGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlanResponse>> {
        const response = await this.listPlansDslPlanDslGetRaw(initOverrides);
        return await response.value();
    }

}
