# coding: utf-8

"""
mmopdca API

Command-DSL-driven forecasting micro-service API only

The version of the OpenAPI document: 0.4.0
Contact: gtocue510@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ActAction(str, Enum):
    """
    ActAction
    """

    """
    allowed enum values
    """
    NOOP = "noop"
    RETRAIN = "retrain"
    ALERT = "alert"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActAction from a JSON string"""
        return cls(json.loads(json_str))
