name: sdk-tests
on:
  push:          { branches: [main, feature/api-only-day1] }
  pull_request:  { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: { matrix: { python: ['3.11'] } }

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with: { python-version: '${{ matrix.python }}' }

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: |
          ${{ runner.os }}-pip-${{ hashFiles('sdk-py/setup.py') }}-${{ hashFiles('requirements-ci.txt') }}

    - name: Install deps
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        # ① ルート（api/ etc. を含む）を editable install
        pip install -e .
        # ② SDK を editable install
        pip install -e sdk-py
        # ③ CI 追加依存
        pip install -r requirements-ci.txt

    - name: Run quickstart
      run: |
        source .venv/bin/activate && python sdk-py/examples/quickstart.py
      env:
        MMOP_BASE_URL: http://localhost:8001   # 必要なら

    - name: Run pytest
      run: |
        source .venv/bin/activate && pytest -q
