# docker/compose.ci.yml  version: '3.9'
services:

  ########################################################################
  # FastAPI (API サーバー)
  ########################################################################
  api:
    build:
      context: ..
      dockerfile: Dockerfile.main_api
    command: >
      python -m uvicorn api.main_api:app
      --host 0.0.0.0 --port 8001 --proxy-headers
    env_file: [ ../.env ]
    tmpfs:
      - /mnt/data/dsl
      - /mnt/checkpoints
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/docs || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12

  ########################################################################
  # Celery Worker
  ########################################################################
  worker:
    build:
      context: ..
      dockerfile: Dockerfile
      target: runtime
    command: celery -A core.celery_app:celery_app worker --loglevel=info
    env_file: [ ../.env ]
    depends_on:
      redis:
        condition: service_started

  ########################################################################
  # Celery Beat
  ########################################################################
  beat:
    build:
      context: ..
      dockerfile: Dockerfile
      target: runtime
    command: >
      celery -A core.celery_app:celery_app
      beat --loglevel=info
      --schedule=/mnt/checkpoints/celerybeat-schedule
    env_file: [ ../.env ]
    depends_on:
      redis:
        condition: service_started

  ########################################################################
  # Redis (Broker)
  ########################################################################
  redis:
    image: redis:7-alpine
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
      --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  ########################################################################
  # PostgreSQL
  ########################################################################
  db:
    image: postgres:16-alpine
    env_file: [ ../.env ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  ########################################################################
  # Exporters & Prometheus
  ########################################################################
  redis-exporter:
    image: oliver006/redis_exporter:v1.60.0
    command:
      - "--redis.addr=redis://default:${REDIS_PASSWORD_ENC}@redis:6379"
    depends_on:
      redis:
        condition: service_started
    ports:
      - "9121:9121"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:9121/metrics"]
      interval: 5s
      timeout: 3s
      retries: 12

  celery-exporter:
    image: danihodovic/celery-exporter:0.9.1
    environment:
      CE_BROKER_URL: redis://default:${REDIS_PASSWORD_ENC}@redis:6379/0
      CE_PORT: 9808
    ports:
      - "9808:9808"
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl -f http://localhost:9808/metrics"]
      interval: 5s
      timeout: 3s
      retries: 12

  prom:
    image: prom/prometheus:v2.52.0
    command:
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=24h
    volumes:
      - ../prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      redis-exporter:
        condition: service_started
      celery-exporter:
        condition: service_started
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:9090/-/ready"]
      interval: 5s
      timeout: 3s
      retries: 12
