name: CI - Docker Stack Health

on:
  push:          { branches: [ main, develop ] }
  pull_request:  {}

jobs:
  compose-health:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    # .env を生成
    - name: Create .env
      run: |
        cat > .env <<'EOF'
        REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD_RAW }}
        REDIS_PASSWORD_ENC=${{ secrets.REDIS_PASSWORD_URL }}
        POSTGRES_DB=mmopdca
        POSTGRES_USER=mmop_user
        POSTGRES_PASSWORD=${{ secrets.PG_PASSWORD }}
        DSL_ROOT=/mnt/data/dsl
        LOG_LEVEL=INFO
        TZ=UTC
        EOF
        head -n 10 .env

    # Stack 起動
    - name: Docker Compose up
      run: |
        docker compose \
          --project-directory "$GITHUB_WORKSPACE" \
          --env-file .env \
          -f docker/compose.ci.yml \
          up -d --build
        docker compose ps

    # 待機ループ
    - name: Wait for endpoints
      run: |
        set -e
        check () { curl -fsSL "http://localhost:$1$2" -o /dev/null; }
        echo "⏳ waiting..."
        for i in {1..30}; do
          if check 8001 /docs && check 9090 / && check 9121 /metrics && check 9808 /metrics; then
            echo "✅ healthy"; exit 0; fi
          sleep 4
        done
        echo "❌ timeout"; docker compose logs --tail=50; exit 1

    - name: Docker Compose down
      if: always()
      run: |
        docker compose \
          --project-directory "$GITHUB_WORKSPACE" \
          --env-file .env \
          -f docker/compose.ci.yml \
          down -v --remove-orphans
