# .github/workflows/stack-health.yml
name: CI - Docker Stack Health

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  compose-health:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env for CI
        run: |
          cat > .env <<'EOF'
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD_RAW }}
          REDIS_PASSWORD_ENC=${{ secrets.REDIS_PASSWORD_URL }}
          POSTGRES_DB=mmopdca
          POSTGRES_USER=mmop_user
          POSTGRES_PASSWORD=${{ secrets.PG_PASSWORD }}
          DSL_ROOT=/mnt/data/dsl
          LOG_LEVEL=INFO
          TZ=UTC
          EOF
          sed -n '1,10p' .env

      - name: Docker Compose up
        run: |
          docker compose \
            --env-file .env \
            -f docker/compose.ci.yml \
            up -d --build
          docker compose ps

      - name: Wait until all endpoints respond 200
        run: |
          set -e
          check() { curl -fsSL "http://localhost:$1$2" -o /dev/null; }
          echo "⏳ Waiting for services..."
          for i in {1..30}; do
            if check 8001 /docs && check 9090 / && check 9121 /metrics && check 9808 /metrics; then
              echo "✅ All endpoints are healthy"
              exit 0
            fi
            sleep 4
          done
          echo "❌ Some endpoints never became healthy"
          docker compose logs --tail=50
          exit 1

      - name: Docker Compose down
        if: always()
        run: |
          docker compose \
            --env-file .env \
            -f docker/compose.ci.yml \
            down -v --remove-orphans

