# .github/workflows/stack-health.yml
name: CI - Docker Stack Health

on:
  push:
    branches: [ main, develop ]   # プッシュ対象ブランチ
  pull_request:

jobs:
  compose-health:
    runs-on: ubuntu-latest

    steps:
      # 0) リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # 1) Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2) .env ファイルを Secrets から生成
      - name: Create .env for CI
        run: |
          cat > .env <<'EOF'
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD_RAW }}
          REDIS_PASSWORD_ENC=${{ secrets.REDIS_PASSWORD_URL }}
          POSTGRES_DB=mmopdca
          POSTGRES_USER=mmop_user
          POSTGRES_PASSWORD=${{ secrets.PG_PASSWORD }}
          DSL_ROOT=/mnt/data/dsl
          LOG_LEVEL=INFO
          TZ=UTC
          EOF
          # 先頭 10 行だけ表示して「隠しておきたい値」が出ていないか確認
          sed -n '1,10p' .env

      # 3) Docker Stack を起動
      - name: Docker Compose up
        run: |
          docker compose \
            --env-file .env \
            -f docker/compose.core.yml \
            -f docker/compose.db.yml \
            -f docker/compose.ports.yml \
            up -d --build
          docker compose ps

      # 4) 各エンドポイントが HTTP 200 を返すまで待機
      - name: Wait until all endpoints respond 200
        run: |
          set -e
          check() { curl -fsSL "http://localhost:$1$2" -o /dev/null; }
          echo "⏳ Waiting for services..."
          for i in {1..30}; do
            if check 8001 /docs && check 9090 / && check 9121 /metrics && check 9808 /metrics; then
              echo "✅ All endpoints are healthy"
              exit 0
            fi
            sleep 4
          done
          echo "❌ Some endpoints never became healthy"
          docker compose logs --tail=50
          exit 1

      # 5) オプション：ユニットテストを実行したい場合
      # - name: Run unit tests
      #   run: pytest

      # 6) 最後にクリーンアップ
      - name: Docker Compose down
        if: always()
        run: |
          docker compose \
            --env-file .env \
            -f docker/compose.core.yml \
            -f docker/compose.db.yml \
            -f docker/compose.ports.yml \
            down -v --remove-orphans
