# .github/workflows/test.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Python と pip キャッシュの準備
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

                # 3) 依存パッケージをインストール
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[dev]"
          pip install -e "sdk-py[dev]"
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi

      # 4) .env ファイルを用意
      - name: Prepare .env
        run: cp .env.ci.example .env

      # 5) mmopdcaスタックを起動
      - name: Start mmopdca stack
        run: |
          docker compose --env-file .env -f docker/compose.ci.yml up -d --build

      # 6) HTTP ヘルスチェックが 200 になるまで待機
      - name: Wait for API health endpoint
        run: |
          for i in {1..30}; do
            if curl --fail --silent http://localhost:8001/health; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done

      #7) pytest を実行
      - name: Run pytest
        run: |
          pytest -q

      # 8) スタックをクリーンアップ
      - name: Tear down mmopdca stack
        if: always()
        run: |
          docker compose -f docker/compose.ci.yml down -v --remove-orphans
